//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitiesInfo_
    {
        public int IdActivitiesInfo { get; set; }
        public Nullable<int> IdActivities { get; set; }
        public Nullable<int> IdActivity { get; set; }
        public Nullable<int> IdModerator { get; set; }
        public Nullable<int> IdJuryOne { get; set; }
        public Nullable<int> IdJuryTwo { get; set; }
        public Nullable<int> IdJuryThee { get; set; }
        public Nullable<int> IdJuryFour { get; set; }
        public Nullable<int> IdJuryFive { get; set; }
    
        public virtual Activities_ Activities_ { get; set; }
        public virtual Activity_ Activity_ { get; set; }
        public virtual JuryAndModerator_ JuryAndModerator_ { get; set; }
        public virtual JuryAndModerator_ JuryAndModerator_1 { get; set; }
        public virtual JuryAndModerator_ JuryAndModerator_2 { get; set; }
        public virtual JuryAndModerator_ JuryAndModerator_3 { get; set; }
        public virtual JuryAndModerator_ JuryAndModerator_4 { get; set; }
        public virtual JuryAndModerator_ JuryAndModerator_5 { get; set; }
    }
}
