//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPlan_
    {
        public int IdActionPlan { get; set; }
        public string NameAction { get; set; }
        public Nullable<int> IdEvent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> IdCity { get; set; }
    
        public virtual City_ City_ { get; set; }
        public virtual Event_ Event_ { get; set; }
    }
}
