//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuryAndModerator_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JuryAndModerator_()
        {
            this.ActivitiesInfo_ = new HashSet<ActivitiesInfo_>();
            this.ActivitiesInfo_1 = new HashSet<ActivitiesInfo_>();
            this.ActivitiesInfo_2 = new HashSet<ActivitiesInfo_>();
            this.ActivitiesInfo_3 = new HashSet<ActivitiesInfo_>();
            this.ActivitiesInfo_4 = new HashSet<ActivitiesInfo_>();
            this.ActivitiesInfo_5 = new HashSet<ActivitiesInfo_>();
        }
    
        public int IdJuryAndModerator { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> IdGender { get; set; }
        public string Email { get; set; }
        public string DateOfBirth { get; set; }
        public Nullable<int> IdCountry { get; set; }
        public string Phone { get; set; }
        public Nullable<int> IdDirectory { get; set; }
        public Nullable<int> IdEvent { get; set; }
        public Nullable<int> IdUser { get; set; }
        public byte[] Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitiesInfo_> ActivitiesInfo_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitiesInfo_> ActivitiesInfo_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitiesInfo_> ActivitiesInfo_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitiesInfo_> ActivitiesInfo_3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitiesInfo_> ActivitiesInfo_4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitiesInfo_> ActivitiesInfo_5 { get; set; }
        public virtual Country_ Country_ { get; set; }
        public virtual Directory_ Directory_ { get; set; }
        public virtual Event_ Event_ { get; set; }
        public virtual Gender_ Gender_ { get; set; }
        public virtual User_ User_ { get; set; }
    }
}
