//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizerParticipants_
    {
        public int IdOrganizerParticipants { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> IdCountry { get; set; }
        public string NumberPhone { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string Photo { get; set; }
        public Nullable<int> IdGender { get; set; }
    
        public virtual Country_ Country_ { get; set; }
        public virtual Gender_ Gender_ { get; set; }
        public virtual User_ User_ { get; set; }
    }
}
